#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_BOOTSTRAP=1
RUN_CHECK=1
CLEAN=0

for arg in "$@"; do
  case "$arg" in
    --skip-bootstrap) RUN_BOOTSTRAP=0 ;;
    --no-check|--skip-check) RUN_CHECK=0 ;;
    --clean) CLEAN=1 ;;
    -h|--help)
      cat <<USAGE
Build a native Arch Linux x86_64 pacman package.

Usage:
  scripts/build-arch-package.sh [--skip-bootstrap] [--skip-check] [--clean]

Output:
  dist/arch/smart-eq-preset-switcher-<version>-1-x86_64.pkg.tar.zst

Notes:
  This script builds the binary through `tauri build --no-bundle`, then uses
  makepkg for final package assembly. It does not hand-roll the .pkg.tar.zst
  archive, so pacman can validate and install the result.
USAGE
      exit 0
      ;;
    *) echo "Unknown argument: $arg" >&2; exit 2 ;;
  esac
done

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

target_root() {
  if [[ -n "${CARGO_TARGET_DIR:-}" ]]; then
    printf '%s\n' "$CARGO_TARGET_DIR"
    return
  fi
  for candidate in \
    "$ROOT_DIR/src-tauri/target" \
    "$ROOT_DIR/.cargo-target" \
    "$ROOT_DIR/../.cargo-target"
  do
    if [[ -d "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return
    fi
  done
  printf '%s\n' "$ROOT_DIR/src-tauri/target"
}

[[ "$(uname -s)" == "Linux" ]] || fail "This Arch package script must be run on Linux."
case "$(uname -m)" in
  x86_64|amd64) ;;
  *) fail "Only Arch x86_64 packages are supported." ;;
esac

if [[ "${EUID}" -eq 0 ]]; then
  fail "Do not run makepkg as root. Run this script as your normal user, then install with sudo pacman -U."
fi

cd "$ROOT_DIR"

if [[ "$CLEAN" -eq 1 ]]; then
  info "Cleaning Arch package output."
  TARGET_DIR="$(target_root)"
  rm -rf dist/arch "$TARGET_DIR/release/bundle"
fi

if [[ "$RUN_BOOTSTRAP" -eq 1 ]]; then
  info "Running Linux bootstrap."
  if [[ "$RUN_CHECK" -eq 1 ]]; then
    "$ROOT_DIR/scripts/bootstrap-linux.sh"
  else
    "$ROOT_DIR/scripts/bootstrap-linux.sh" --skip-check
  fi
else
  info "Skipping bootstrap."
fi

if [[ "$RUN_CHECK" -eq 1 && "$RUN_BOOTSTRAP" -eq 0 ]]; then
  info "Running project check."
  npm run check
fi

for cmd in node npm cargo makepkg tar zstd; do
  have "$cmd" || fail "Required command not found: $cmd"
done

PKG_NAME="smart-eq-preset-switcher"
PKG_VERSION="$(node -p "require('./package.json').version")"
PKG_RELEASE="1"
PKG_ARCH="x86_64"
OUT_DIR="$ROOT_DIR/dist/arch"
MAKEPKG_DIR="$OUT_DIR/makepkg"
BIN_NAME="smart_eq_preset_switcher"
ICON_NAME="com.myhli.smarteqpresetswitcher"

info "Building release binary with Tauri production asset embedding, without Tauri bundlers."
npm run tauri -- build --no-bundle

TARGET_DIR="$(target_root)"
BIN="$TARGET_DIR/release/$BIN_NAME"
[[ -x "$BIN" ]] || fail "Release binary not found: $BIN"

info "Preparing makepkg workspace."
rm -rf "$MAKEPKG_DIR"
mkdir -p "$MAKEPKG_DIR"
install -Dm755 "$BIN" "$MAKEPKG_DIR/$BIN_NAME.real"
install -Dm644 "$ROOT_DIR/LICENSE" "$MAKEPKG_DIR/LICENSE"
install -Dm644 "$ROOT_DIR/src-tauri/icons/icon.png" "$MAKEPKG_DIR/icon.png"

cat > "$MAKEPKG_DIR/$BIN_NAME.wrapper" <<'WRAPPER'
#!/usr/bin/env bash
set -euo pipefail

# KDE Plasma + NVIDIA + WebKitGTK can crash on native Wayland with:
#   Gdk-Message: Error 71 (Protocol error) dispatching to Wayland display
# Force XWayland/X11 by default for the GUI process. Users can opt into native
# Wayland for testing with SMART_EQ_USE_WAYLAND=1.
if [[ "${SMART_EQ_USE_WAYLAND:-0}" != "1" ]]; then
  export GDK_BACKEND=x11
  export WINIT_UNIX_BACKEND=x11
  export GDK_RENDERING=image
  export WEBKIT_DISABLE_DMABUF_RENDERER=1
  export WEBKIT_DISABLE_COMPOSITING_MODE=1
fi

exec /usr/lib/smart-eq-preset-switcher/smart_eq_preset_switcher "$@"
WRAPPER
chmod +x "$MAKEPKG_DIR/$BIN_NAME.wrapper"

cat > "$MAKEPKG_DIR/$ICON_NAME.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=SmartEQPresetSwitcher
Comment=Cross-platform EQ preset switcher with Linux EQ exports
Exec=smart-eq-preset-switcher --gui
Icon=$ICON_NAME
Terminal=false
Categories=Audio;AudioVideo;Utility;
StartupNotify=true
DESKTOP

cat > "$MAKEPKG_DIR/PKGBUILD" <<PKGBUILD
# Generated by scripts/build-arch-package.sh. Do not edit in place.
pkgname=$PKG_NAME
pkgver=$PKG_VERSION
pkgrel=$PKG_RELEASE
pkgdesc='Cross-platform EQ preset switcher with Windows Equalizer APO and Linux PipeWire export support'
arch=('$PKG_ARCH')
url='https://github.com/smyhlin/SmartEQPresetSwitcher'
license=('MIT')
depends=('webkit2gtk-4.1' 'gtk3' 'libayatana-appindicator' 'librsvg')
optdepends=('pipewire: Linux EQ export workflows')
source=()
sha256sums=()

package() {
  install -Dm755 "\$srcdir/../$BIN_NAME.real" "\$pkgdir/usr/lib/$PKG_NAME/$BIN_NAME"
  install -Dm755 "\$srcdir/../$BIN_NAME.wrapper" "\$pkgdir/usr/bin/smart-eq-preset-switcher"
  install -Dm644 "\$srcdir/../LICENSE" "\$pkgdir/usr/share/licenses/$PKG_NAME/LICENSE"
  install -Dm644 "\$srcdir/../icon.png" "\$pkgdir/usr/share/icons/hicolor/256x256/apps/$ICON_NAME.png"
  install -Dm644 "\$srcdir/../$ICON_NAME.desktop" "\$pkgdir/usr/share/applications/$ICON_NAME.desktop"
}
PKGBUILD

info "Creating pacman package with makepkg."
mkdir -p "$OUT_DIR"
(
  cd "$MAKEPKG_DIR"
  PKGDEST="$OUT_DIR" makepkg --force --nodeps --noextract --noprepare --nocheck
)

PKG_FILE="$OUT_DIR/$PKG_NAME-$PKG_VERSION-$PKG_RELEASE-$PKG_ARCH.pkg.tar.zst"
[[ -f "$PKG_FILE" ]] || fail "makepkg did not produce expected package: $PKG_FILE"

info "Arch package artifact: $PKG_FILE"
info "Install with: sudo pacman -U '$PKG_FILE'"
